config/routes.rb
PhonicPanel::Application.routes.draw do
  resources :sound_clips


  resources :sound_boards


  match '/auth/:provider/callback', :to => 'sessions#create'

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  attr_accessible :provider, :uid, :user_id, :user

  belongs_to :user
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_with_omniauth(auth)
    find_by_provider_and_uid(auth['provider'], auth['uid'])
  end

  def self.create_with_omniauth(authorization_hash, user = nil)
    user ||= User.create_with_omniauth(authorization_hash)
    Authorization.create(:user => user, :uid => authorization_hash['uid'], :provider => authorization_hash['provider'])
  end
end

app/models/sound_board.rb
class SoundBoard < ActiveRecord::Base
  attr_accessible :name, :user_id

  belongs_to :user
  has_many :sound_clips
end

app/models/sound_clip.rb
class SoundClip < ActiveRecord::Base
  attr_accessible :descriptions, :sound_board_id, :title

  belongs_to :sound_board
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name
  has_many :authorizations
  has_many :sound_boards

  def self.create_with_omniauth(auth)
    create!(:name => auth['info']['nickname'])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def signed_in?
    !!current_user
  end

  helper_method :current_user, :signed_in?

  def current_user=(user)
    @current_user = user
    session[:user_id] = user.id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    authorization = request.env['omniauth.auth']

    unless @auth = Authorization.find_with_omniauth(authorization)
      @auth = Authorization.create_with_omniauth(authorization, current_user)
    end

    self.current_user = @auth.user

    render :text => "Welcome, #{current_user.name}."
  end
end

app/controllers/sound_boards_controller.rb
class SoundBoardsController < ApplicationController
  # GET /sound_boards
  # GET /sound_boards.json
  def index
    @sound_boards = SoundBoard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sound_boards }
    end
  end

  # GET /sound_boards/1
  # GET /sound_boards/1.json
  def show
    @sound_board = SoundBoard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sound_board }
    end
  end

  # GET /sound_boards/new
  # GET /sound_boards/new.json
  def new
    @sound_board = SoundBoard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sound_board }
    end
  end

  # GET /sound_boards/1/edit
  def edit
    @sound_board = SoundBoard.find(params[:id])
  end

  # POST /sound_boards
  # POST /sound_boards.json
  def create
    @sound_board = SoundBoard.new(params[:sound_board])

    respond_to do |format|
      if @sound_board.save
        format.html { redirect_to @sound_board, notice: 'Sound board was successfully created.' }
        format.json { render json: @sound_board, status: :created, location: @sound_board }
      else
        format.html { render action: "new" }
        format.json { render json: @sound_board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sound_boards/1
  # PUT /sound_boards/1.json
  def update
    @sound_board = SoundBoard.find(params[:id])

    respond_to do |format|
      if @sound_board.update_attributes(params[:sound_board])
        format.html { redirect_to @sound_board, notice: 'Sound board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sound_board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sound_boards/1
  # DELETE /sound_boards/1.json
  def destroy
    @sound_board = SoundBoard.find(params[:id])
    @sound_board.destroy

    respond_to do |format|
      format.html { redirect_to sound_boards_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sound_clips_controller.rb
class SoundClipsController < ApplicationController
  # GET /sound_clips
  # GET /sound_clips.json
  def index
    @sound_clips = SoundClip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sound_clips }
    end
  end

  # GET /sound_clips/1
  # GET /sound_clips/1.json
  def show
    @sound_clip = SoundClip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sound_clip }
    end
  end

  # GET /sound_clips/new
  # GET /sound_clips/new.json
  def new
    @sound_clip = SoundClip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sound_clip }
    end
  end

  # GET /sound_clips/1/edit
  def edit
    @sound_clip = SoundClip.find(params[:id])
  end

  # POST /sound_clips
  # POST /sound_clips.json
  def create
    @sound_clip = SoundClip.new(params[:sound_clip])

    respond_to do |format|
      if @sound_clip.save
        format.html { redirect_to @sound_clip, notice: 'Sound clip was successfully created.' }
        format.json { render json: @sound_clip, status: :created, location: @sound_clip }
      else
        format.html { render action: "new" }
        format.json { render json: @sound_clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sound_clips/1
  # PUT /sound_clips/1.json
  def update
    @sound_clip = SoundClip.find(params[:id])

    respond_to do |format|
      if @sound_clip.update_attributes(params[:sound_clip])
        format.html { redirect_to @sound_clip, notice: 'Sound clip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sound_clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sound_clips/1
  # DELETE /sound_clips/1.json
  def destroy
    @sound_clip = SoundClip.find(params[:id])
    @sound_clip.destroy

    respond_to do |format|
      format.html { redirect_to sound_clips_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sound_boards_helper.rb
module SoundBoardsHelper
end

app/helpers/sound_clips_helper.rb
module SoundClipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhonicPanel</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sound_boards/_form.html.erb
<%= form_for(@sound_board) do |f| %>
  <% if @sound_board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sound_board.errors.count, "error") %> prohibited this sound_board from being saved:</h2>

      <ul>
      <% @sound_board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sound_boards/edit.html.erb
<h1>Editing sound_board</h1>

<%= render 'form' %>

<%= link_to 'Show', @sound_board %> |
<%= link_to 'Back', sound_boards_path %>

app/views/sound_boards/index.html.erb
<h1>Listing sound_boards</h1>

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sound_boards.each do |sound_board| %>
  <tr>
    <td><%= sound_board.name %></td>
    <td><%= sound_board.user_id %></td>
    <td><%= link_to 'Show', sound_board %></td>
    <td><%= link_to 'Edit', edit_sound_board_path(sound_board) %></td>
    <td><%= link_to 'Destroy', sound_board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sound board', new_sound_board_path %>

app/views/sound_boards/new.html.erb
<h1>New sound_board</h1>

<%= render 'form' %>

<%= link_to 'Back', sound_boards_path %>

app/views/sound_boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sound_board.name %>
</p>

<p>
  <b>User:</b>
  <%= @sound_board.user_id %>
</p>


<%= link_to 'Edit', edit_sound_board_path(@sound_board) %> |
<%= link_to 'Back', sound_boards_path %>

app/views/sound_clips/_form.html.erb
<%= form_for(@sound_clip) do |f| %>
  <% if @sound_clip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sound_clip.errors.count, "error") %> prohibited this sound_clip from being saved:</h2>

      <ul>
      <% @sound_clip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :descriptions %><br />
    <%= f.text_field :descriptions %>
  </div>
  <div class="field">
    <%= f.label :sound_board_id %><br />
    <%= f.number_field :sound_board_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sound_clips/edit.html.erb
<h1>Editing sound_clip</h1>

<%= render 'form' %>

<%= link_to 'Show', @sound_clip %> |
<%= link_to 'Back', sound_clips_path %>

app/views/sound_clips/index.html.erb
<h1>Listing sound_clips</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Descriptions</th>
    <th>Sound board</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sound_clips.each do |sound_clip| %>
  <tr>
    <td><%= sound_clip.title %></td>
    <td><%= sound_clip.descriptions %></td>
    <td><%= sound_clip.sound_board_id %></td>
    <td><%= link_to 'Show', sound_clip %></td>
    <td><%= link_to 'Edit', edit_sound_clip_path(sound_clip) %></td>
    <td><%= link_to 'Destroy', sound_clip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sound clip', new_sound_clip_path %>

app/views/sound_clips/new.html.erb
<h1>New sound_clip</h1>

<%= render 'form' %>

<%= link_to 'Back', sound_clips_path %>

app/views/sound_clips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @sound_clip.title %>
</p>

<p>
  <b>Descriptions:</b>
  <%= @sound_clip.descriptions %>
</p>

<p>
  <b>Sound board:</b>
  <%= @sound_clip.sound_board_id %>
</p>


<%= link_to 'Edit', edit_sound_clip_path(@sound_clip) %> |
<%= link_to 'Back', sound_clips_path %>